version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/malutrom
    #source: codedeploy/zz_malutrom.conf
    #destination: /etc/httpd/conf.d/
hooks:
  ApplicationStart:
    - location: codedeploy/install.sh
